steps:  
  # Install Python dependencies
  - name: python
    entrypoint: pip
    args: ['install', '--upgrade',  '--user', '--requirement', 'requirements.txt']    
  # Install Python dependencies and run cleanup script
  - name: python
    entrypoint: /bin/sh
    args:
    - -c
    - 'python3 workspace/run_pipeline.py'
    env: 
    - 'PYTHONPATH=/workspace/'
    - 'GCP_PROJECT_ID=$PROJECT_ID'
    - 'GCP_BUCKET_NAME=${_GCP_BUCKET_NAME}'
    - 'GCP_REGION=${_GCP_REGION}'
timeout: 86400s
